# Generated by Django 2.2.5 on 2019-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Banda')),
                ('musicStyle', models.CharField(max_length=150, verbose_name='Estilo Musical')),
                ('originLocal', models.CharField(max_length=100, verbose_name='Local de Origem')),
                ('formationAt', models.IntegerField(verbose_name='Formada em')),
            ],
        ),
    ]
